name: Build & Test & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
#        cache: 'npm'
    - name: Install PNPM
      run: npm install -g pnpm
    - run: pnpm install
    - run: pnpm run lint
    - run: BASE_URL=/ss-2025/ VITE_URL_DATA=https://luk7.smallhost.pl/ss/ pnpm run build
    - name: Upload artifact for deployment
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./dist
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
